itle: "My Chess Openings"
description: "A guide to chess openings"
theme: minima
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""  # Dotyczy wszystkich plików
      type: "pages"
    values:
      layout: "default"
